steps:
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']
    dir: 'functions'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        firebase deploy --only functions
    dir: 'functions'
