// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXDJx-XwR5WnXxa57SPB4YUrMyu5YxOM',
    appId: '1:537702287657:web:0497f74dd48ce2550d4f38',
    messagingSenderId: '537702287657',
    projectId: 'orca-471102',
    authDomain: 'orca-471102.firebaseapp.com',
    storageBucket: 'orca-471102.firebasestorage.app',
    measurementId: 'G-7Y1EXB4ZCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPJaZL061ZmSpCUkFCXZeUcgHzYhmUtq0',
    appId: '1:537702287657:android:8462771dde37362f0d4f38',
    messagingSenderId: '537702287657',
    projectId: 'orca-471102',
    storageBucket: 'orca-471102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9D3aJfWjXJvGxVYIPBy22_1684LlkGHI',
    appId: '1:537702287657:ios:449c6e2a5b833b810d4f38',
    messagingSenderId: '537702287657',
    projectId: 'orca-471102',
    storageBucket: 'orca-471102.firebasestorage.app',
    iosBundleId: 'com.example.orca',
  );

}